version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-weather
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    env_file:
      - .env
    command: npm run start:dev
volumes:
  pgdata:
